services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ${PWD}:/var/www/html:z
      - ./storage:/var/www/html/storage:z
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:z
    networks:
      - mysql_shared_network
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ${PWD}:/var/www/html:z
      - ./storage:/var/www/html/storage:z
    entrypoint: ["/var/www/html/docker/php/entrypoint.sh"]
    command: ["php-fpm"]
    networks:
      - mysql_shared_network

volumes:
  storage_data:

networks:
  mysql_shared_network:
    external: true
